language: php

dist: bionic

notifications:
    email: false

php:
    - "7.1"
    - "7.2"
    - "7.3"
    - "7.4snapshot"

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_finish: true
    allow_failures:
        - php: "7.4snapshot"

before_script:
    - composer create-project oxid-esales/graphql-module --repository packages.json --remove-vcs -n

script:
    - cd graphql-module
    - composer test:syntax
    - composer test:lint
    - composer test:static
